### ISSUE TITLE
Windows Installer (guide) failed 

### ISSUE THREAD

**Issue by Nozziel** [OPM/opm-core#1083]
RUNNING FLOW IN A VIRTUAL MACHINE: http://opm-project.org/?page_id=294

Following the steps Install runs perfectly and then the site directs you to "MY FIRST RESERVOIR SIMULATION" and states to start at step 3 (http://opm-project.org/?page_id=197)

**but unzip and flow** are not actually installed. (after installing unzip  (googled command) and flow by doing step 2 of MY FIRST RESERVOIR SIMULATION ) but that still does not help for now flow gives an error

Command and error I get:
vagrant@vagrant-ubuntu-trusty-64:~/opm-data-master/spe1$ flow SPE1CASE1.DATA

**flow: error while loading shared libraries: libopmcore.so.2015: cannot open shared object file: No such file or directory**

**How I fixed the final problem** I think it was just:
sudo apt-get install libopm-simulators-bin

but I also did the command below that also had some stuff to do
sudo apt-get upgrade 

either the site need some extra info with commands or the install script needs a tweak :)

_Note: I actually did have a install issue (vagrant up ->VMBox would not start with VT-x error, VT-x was enabled in BIOS but Hyper-V was enabled in windows, turning that off in windows, I issued vagrant up again and everything ran without complaining)_

**Comment by atgeirr** [comment]
I just went through the tutorial myself with a clean VM without problems. However I did notice that it was not clearly specified that you should use the "vagrant_opm_user" directory (under opm-utilities), and in some of the figures it looked like the "vagrant" directory was used instead (although that was just an unlucky accident of cutting the output). The text has now been updated to clarify the directory to use, and the figures will be updated shortly.

I am pretty sure your problems stem from using the "vagrant" (intended for developers) and not the "vagrant_opm_user" dir, and since I found no problems other than as described above, I'll close this issue. Please reopen if you have further problems.

Finally:
> Note: I actually did have a install issue (vagrant up ->VMBox would not start with VT-x error, VT-x was enabled in BIOS but Hyper-V was enabled in windows, turning that off in windows, I issued vagrant up again and everything ran without complaining)

Since I am not familiar with Windows, I do not know the details of this. Do you think we should say something about this in the tutorial? If so, what?

**Comment by Nozziel** [comment]
I guess you could add a quick tip at the VMBox section, maybe something like:
_Tip: To run VMBox you might need to enable VT-X in your bios and you might need to turn of Hyper-V in windows._

That should be enough directions I think for the OPM site, more  details can then be easily googled for :)

**Comment by atgeirr** [comment]
Thanks, I added it to the page.
