### ISSUE TITLE
Issue with building opm-core from source

### ISSUE THREAD

**Issue by rinauoy** [OPM/opm-core#801]
Dear Friends, 

I have been trying to build opm-core module from source. I have followed instructions and encountered the attached error. 
![screenshot from 2015-05-08 08 25 20](https://cloud.githubusercontent.com/assets/9147160/7539589/e20e6288-f55c-11e4-8a1c-c68d3c6cd7de.png)

I would really appreciate if anyone could help. 

Regards, 

Rina

**Comment by bska** [comment]
Hi Rina,

From an initial glance, this **looks** like a version mismatch between the opm-core and the ERT libraries.  Did you use the latest Git sources of all components, some of them, or none of them?

Or maybe I should ask the question differently: What instructions (link) did you follow that led to the build failure?

**Comment by rinauoy** [comment]
Hi Bard, 

Thanks for your reply.

I just got the opm-core-master zip today and other prerequisite components as stated in ReadMe file in opm-core-master folder. I referred the steps in ReadMe file as instructions. 

Cheers, 

Rina

**Comment by bska** [comment]
Hi Rina,

Thanks for the update and sorry about the late reply. When you say

> I referred the steps in ReadMe file as instructions.

I just want to be clear that you mean the [`README`](https://github.com/OPM/opm-core/blob/master/README) in opm-core's top-level directory.

From your screenshot you appear to be running Ubuntu 14.04 LTS (Trusty Tahr), but please correct me if I'm wrong.  One of the steps in the instructions mentioned earlier is to install the ERT libraries using the command
```sh
sudo apt-get install ert.ecl
```
On Ubuntu 14.04 that will get you the 2015.04 release of the ERT libraries. I'm afraid I don't remember the exact details, but there was a recent breaking change (Ensembles/ert@613366c) in the ERT libraries that might not have made it into the 2015.04 release.  I'll ask the ERT (and OPM) developer @joakim-hove to set the records straight.

In any case, the current master sources of opm-core depend on the breaking change in ERT being in place.  If the ert.ecl package does not include that change, then at the very least the instructions in the README file are inaccurate (or, more bluntly, wrong).  If you are going to continue using the master sources of opm-core, then I recommend that you remove the pre-pacakged version of the ERT (`sudo apt-get remove ert.ecl`) and also switch to using the master (Git) [sources](https://github.com/Ensembles/ert) of the ERT.  Otherwise, you should probably switch to using the 2015.04 release branch.

I'm sorry that I can't be more helpful at the moment.

**Comment by joakim-hove** [comment]
> I'm afraid I don't remember the exact details, but there was a recent breaking change (Ensembles/ert@613366c) in the ERT libraries that might not have made it into the 2015.04 release. 

Yes - that is unfortunately correct[1]; right after the 2015.04 release the ert library was updated so that when using ert and opm-core you must either:

-  Use the 2015.04 binary release of both ert and opm.

or 

- Use the development (i.e. git sources) versions for both ert and opm.

Sorry about the inconvenience. If you intend to experiment with/develop OPM code you should:

1. `sudo apt-get remove ert.el` - that is really important; if you have both the developement and binary version of ert installed together the possibilities for subsequent build problems and confusion is endless.
2. Build and install ert:
```
git clone git@github.com:Ensembles/ert.git
cd ert
mkdir build ; cd build
cmake ../devel
make
sudo make install
```
3. Rebuild `opm-parser` (might be wise to wipe the build/ directory).
4. Continue with `opm-core`

[1]: And looking at your build errors I can indeed confirm that this is what is happening.

**Comment by rinauoy** [comment]
Hi @bska , 

Indeed, I am running Ubuntu 14.04 LTS. I followed the README in opm-core's top-level directory.

Thanks very much. That is very helpful, actually. 

Hi @joakim-hove 

Appreciate your comment. I think I see the problems now.

**Comment by atgeirr** [comment]
Did you succeed in building OPM @rinauoy? If so, please close this issue.

**Comment by rinauoy** [comment]
Yeah, I did. Thanks very much.
