### ISSUE TITLE
OPM-core on mac os x 

### ISSUE THREAD

**Issue by rinauoy** [OPM/opm-core#913]
Dear Friends, 

I am trying to make opm-core library work on mac os x. It seemed that I could not make it work. 

I have followed this instruction;

You can build opm-core with Apple Xcode 4.6 or later, Ruby 1.9 or later
and the Homebrew port system:

# activate necessary repositories
```
brew tap homebrew/science
brew tap opm/opm
```
# libraries necessary for OPM
```
caffeinate brew install suite-sparse superlu ert.ecl
caffeinate brew install --with-c++11 boost tinyxml dune-istl
```
I got errors when I paste this part to terminal: caffeinate brew install suite-sparse super ert.ecl

I would really appreciate if anyone could guide me to make it work. 

Thanks,

Rina

**Comment by bska** [comment]
> I got errors when I paste this part to terminal: `caffeinate brew install suite-sparse super ert.ecl`
> 
> I would really appreciate if anyone could guide me to make it work.

I'm not an export on OS X so I don't think I'll have a lot to contribute to this, but would you mind posting the actual error messages you got from the `caffeinate` command?

**Comment by joakim-hove** [comment]
I am quite sure there is no ert.ecl package for Mac OSX - so that you must a least install first:

1. git clone git@github.com:Ensembles/ert.git
2. cd ert 
3. mkdir build ; cd build
4. cmake ../devel   
5. make ; make install

Whether there are Mac OSX packages for suite-sparse and super(LU) I do not know.

Then you can start on building opm proper - see instructions here: http://www.opm-project.org/download.php - however observe that there is a new top level package opm-common: https://github.com/OPM/opm-common which is *very much* needed for the build process.


However: observe that there are several core opm-developers who use Mac as their daily platform, so it is certainly possible!

**Comment by atgeirr** [comment]
The Homebrew opm scripts have not been maintained, but we are in the middle of a release process and part of that is making sure installation instructions are correct. I am not sure how much effort it would take  to update the homebrew, so building from source may be the solution we'll support. I'll report back on this later.

**Comment by rinauoy** [comment]
Thank everyone. I have managed to build from sources on Mac Os now with latest instructions.
