### ISSUE TITLE
RelpermDiagnostics test triggers assert() in debug mode

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-core#935]
Running test_relpermdiagnostics in debug mode triggers this assert:
```
Assertion failed: (rowIdx > 0), function extractUnscaledSwof_, file /Users/atgeirr/opm-build-debug/opm-material/opm/material/fluidmatrixinteractions/EclEpsScalingPoints.hpp, line 374.
```

The problem is: the opm-material code checks for the same error condition as the test (the first entry in the krw column of SWOF must be zero) and `assert()`s it. There is a conflict in assumptions:
 - the opm-polymer code assumes that it cannot encounter this error, in other words, that the parser never will pass on a table with this error
 - opm-parser does not check this, leaving interpretation of tables to user code

I think that the opm-parser assumption must be kept here (i.e. not checking that all tables can be interpreted correctly), because this can be quite complicated (which in turn is part of the reason for wanting a relperm diagnostics tool). Therefore, the assumption made in opm-material is wrong and it must change, removing the `assert()` and either being "tolerant" in some way with respect to this kind of error, throwing an exception or (perhaps best) applying the `ParseMode` feature to choose how to treat the situation.

Do you agree, @andlaus, @joakim-hove and @qilicun?

(And yes, this issue could have been placed in opm-material.)

**Comment by andlaus** [comment]
> opm-parser does not check this, leaving interpretation of tables to user code

isn't opm-material considered "user code" here?

> Do you agree, @andlaus, @joakim-hove and @qilicun?

in principle yes, but I don't really get your point: Is the issue related to some unit test in opm-core triggering an assertion in opm-material because some intentionally incorrect data was passed? In that case I'm not so sure if it should always be detected (and the opm-material `assert()` should be replaced by an exception) or only if it should only be detected by the relperm diagnostics tool. (Note that since I don't have to create those decks, I'm largely indifferent if the simulator catches such errors or not...)

**Comment by atgeirr** [comment]
I see that I made a mistake above, I said opm-polymer when I meant opm-material! Corrected:

The problem is: the opm-material code checks for the same error condition as the test (the first entry in the krw column of SWOF must be zero) and assert()s it. There is a conflict in assumptions:

 - the opm-*material* code assumes that it cannot encounter this error, in other words, that the parser never will pass on a table with this error
 - opm-parser does not check this, leaving interpretation of tables to user code

> isn't opm-material considered "user code" here?

Yes.


> I'm not so sure if it should always be detected (and the opm-material assert() should be replaced by an exception) or only if it should only be detected by the relperm diagnostics tool.

I am not sure either. Since the release version ran fine it may be that the opm-material assert() is not necessary to avoid crashing or undefined behaviour. If so, perhaps removing the assert() entirely is an option. Then we can insert the relperm diagnostics tool in all simulators to catch such user errors instead.

**Comment by andlaus** [comment]
> If so, perhaps removing the assert() entirely is an option. Then we can insert the relperm diagnostics tool in all simulators to catch such user errors instead.

I'm certainly open for that, so open a PR for this if you think this is The Right Way (TM) and I'll merge.

**Comment by joakim-hove** [comment]
I will answer properly tomorrow; but the brief answer is that the table
Code is one of my blind spots in the parser, and that on å general basis I
prefer throw(..) to assert(..).
14. des. 2015 15:23 skrev "Atgeirr Flø Rasmussen" <notifications@github.com>
følgende:

**Comment by andlaus** [comment]
> on a general basis I prefer throw(..) to assert(..).

I'm a bit more differentiated here: if the `if` could possibly have a performance impact, I prefer the `assert()` for stuff which is supposed to rarely trigger. As the (amount of trouble)/(performance hit) ratio gets larger, the likelihood of me using explicit exceptions also gets larger. (at least that's what I try to do.)

**Comment by alfbr** [comment]
Please note that in this case the diagnostics code is the user. The parser is doing exactly what we need, parsing. Throwing in opm-parser will need to be accompanied by parsemode options. I am not sure it makes sense to prioritise that now. Opm-material is a bit more tricky, but unless it creates internal inconsistencies in the material code, I suggest leaving checks to the diagnostics code. The diagnostics code is currently standalone, but the intention is to make its functionality available for all simulators in need. Hence, the intention is to have that as the authoritative place for consistency checks. Starting to implement the same checks in material or parser in parallel is problematic.

**Comment by qilicun** [comment]
For this case, I think it's better to use relperm diagnostics tool to
detect all the warnings and errors and not throw immediately. because the
deck maybe have other issues, if we meet one and throw one, this will
bother the users. After diagnosis the whole deck file, if real *errors*
detected, then we can throw and output clearly messages to the users.

2015-12-15 2:54 GMT+08:00 Alf Birger Rustad <notifications@github.com>:

**Comment by andlaus** [comment]
@alfbr 
> The diagnostics code is currently standalone, but the intention is to make its functionality available for all simulators in need.

I as stated above, I do not object to removing the consistency checks in opm-material. That said, your point seems like a pretty strong argument to move the diagnostics code to the same place as where the interpretation of the satfunc input data happens IMO (i.e., moving them from opm-core to opm-material).

@qilicun 
> For this case, I think it's better to use relperm diagnostics tool to detect all the warnings and errors and not throw immediately.

isn't it better to just print warnings instead of throwing up?

**Comment by qilicun** [comment]
@andlaus 

My point is "because the
deck maybe have other issues, if we meet one and throw one, this will
bother the users. After diagnosis the whole deck file, if real *errors*
detected, then we can throw and output clearly messages to the users."

We need to distinguish ``error`` and ``warning``, if error happens, throw is the best way.

**Comment by alfbr** [comment]
> moving them from opm-core to opm-material

This quickly becomes a question about module organisation. For now, the code is stand-alone, and put in opm-core. We can revisit this topic when the code matures a bit, then we will know better where it fits.

**Comment by joakim-hove** [comment]
> Therefore, the assumption made in opm-material is wrong and it must change, removing the assert()

The `assert( )` has been removed - but it was there for a reason; now the whole thing just breaks hard after the `assert( ... )`. See also: #941

**Comment by qilicun** [comment]
I will look into this, But from my first guess, this error is not due to test data and relperm diagnostics, because the LOGFILE from this binary looks very good and the results is as expected.

**Comment by qilicun** [comment]
The error message is
``unknown location(0): fatal error in "diagnosis": std::invalid_argument: Value: 18446744073709551615 out of range: [0,15)``

In the test data file, SWOF has 15 rows, I suspect that this message comes from new parser tables implementation
https://github.com/OPM/opm-parser/blob/master/opm/parser/eclipse/EclipseState/Tables/TableColumn.cpp#L109

Because in the test data we just change the first value of krw column in SWOF, this should has no relation with number of rows, even if you change the invalid value back to a valid value, the error still happen, until you disable all the boost check.  But I just wonder where is this strange value ``18446744073709551615 `` in the error message output by parser comes from?

**Comment by joakim-hove** [comment]
The error happens here: https://github.com/OPM/opm-material/blob/master/opm/material/fluidmatrixinteractions/EclEpsScalingPoints.hpp#L369 where we look up element `rowIdx - 1` - the value `18446744073709551615` is size_t wrapping around.

**Comment by qilicun** [comment]
I see.  But the strange thing is that even I modified the SWOF table in the test data file, the error still happen, did you have any thoughts?

**Comment by qilicun** [comment]
I see, sorry for that, I will fix this.

**Comment by qilicun** [comment]
I think https://github.com/OPM/opm-core/pull/942 will fix this issue. please test if it works.

**Comment by andlaus** [comment]
> The error happens here: https://github.com/OPM/opm-material/blob/master/opm/material/fluidmatrixinteractions/EclEpsScalingPoints.hpp#L369 where we look up element `rowIdx - 1` - the value `18446744073709551615` is size_t wrapping around.    

I might be wrong, but did you last opm-material PR not remove the assert() which prevented this?

**Comment by joakim-hove** [comment]
> I might be wrong, but did you last opm-material PR not remove the assert() which prevented this?

That is right; but it was a *real problem* - previously it was caught in an `assert( ... )` - now in a range error; same same but different :-)

**Comment by andlaus** [comment]
hm. that issue seems to be a bit deeper, then: the relperm code in opm-material will crash if such a thing happens (i.e., it cannot silently assume that the data is "correct enough") one way to fix this is to catch such errors already in opm-parser (which is basically a layering violation). another alternative is that the relperm diagnostics code is required to check it before it instantiates the material law parameters (which adds subtle implicit assumptions that make the code hard to understand). Both seem to be not very desirable to me...

**Comment by alfbr** [comment]
It seems this is an example of internal inconsistency in opm-material that I feared. Hopefully there are not many of those. Please allow Liu Ming and myself some time to discuss and see if we can find a way forward with consensus.

**Comment by joakim-hove** [comment]
> that issue seems to be a bit deeper [...]

I agree. The parser guarantees:

- Order - i.e. INCREASING / DECREASING is correct.
- All elements have a value; i.e. no defaults.

The parser is completely ignorant to the questions we are discussing now; however that could  easily  change.

**Comment by andlaus** [comment]
> The parser is completely ignorant to the questions we are discussing now; however that could easily change.

this means all you think its best to the relperm diagnostics code should move from opm-core to opm-parser? (i.e., higher level code should be able to assume that the tables have enough entries?)

**Comment by joakim-hove** [comment]
> this means all you think its best to the relperm diagnostics code should move from opm-core to opm-parser? (i.e., higher level code should be able to assume that the tables have enough entries?)

I am mostly trying to state the current state as I see it; as for possible changes I have not thought much about it; but diagnostic + error checking could certainly go further down, i.e. to the parser. That way down stream code could make stronger assumptions.

**Comment by andlaus** [comment]
> diagnostic + error checking could certainly go further down, i.e. to the parser

hm, that's probably also not a terribly good idea: uncovering some errors requires a more or less full understanding of the meaning of the data of these tables and their interactions with other keywords, e.g., the requirements for the end points for end-point scaling. possibly, the solution is that the parser guarantees that the tables "are correct enough to be used". This could mean that it guarantees that for certain tables there is more than one row...

**Comment by atgeirr** [comment]
Revisiting this issue to see if it can be closed. Certainly the symptom is no longer there (the test failure), but was this resolved in a good way? Which part of the code is responsible for checking for invalid table data? I'd especially appreciate @joakim-hove, @andlaus or @qilicun's input on this.

**Comment by joakim-hove** [comment]
Hello;

> Which part of the code is responsible for checking for invalid table data?

I guess that is not as clear as it should. With all disclaimers applied this is my view of the table code:

1. The tables are read from the input deck and stored in the table classes in the parser: https://github.com/OPM/opm-parser/tree/master/opm/parser/eclipse/EclipseState/Tables

2. In opm-material there is table foo; the table implementation in opm-material should work irrespecive of whether opm-parser is present or not - it is my unqualified gut feeling that quite a lot of table related functionality is duplicated between these two modules.

3. And then - everything is copied to even another datastructure in opm-core.

I would actually think that it should be possible to collapse this to only use the classes from opm-parser, but I have not looked into this in detail.

In opm-parser the only validation is that (Strictly?) increasing / decreasing properties of a column and whether the column values can be defaulted is enforced during load. See eg: https://github.com/OPM/opm-parser/blob/master/opm/parser/eclipse/EclipseState/Tables/Tables.cpp#L193

**Comment by atgeirr** [comment]
> And then - everything is copied to even another datastructure in opm-core.

I don't think that is true any more, but it was before we switched to opm-material.

> In opm-parser the only validation is that (Strictly?) increasing / decreasing properties of a column and whether the column values can be defaulted is enforced during load

Good to know. So the question is then: does the opm-material code check the validity of its input tables or not? What should be left for the diagnostics, and what must still be checked in opm-material?

**Comment by andlaus** [comment]
> it is my unqualified gut feeling that quite a lot of table related functionality is duplicated between these two modules.

I tried to avoid that and keep the code as disjoint as possible.the motivation is the following:

- the opm-material code occasionally needs to fuse information provided by opm-parser. e.g. the satfunc code works the same irrespectable of whether family 1 or family 2 keywords are used
- most of the table-related functionality of opm-material is about evaluating them at a given point. (which, I agree, is a functionality that is also present in opm-parser). this functionality cannot be moved to opm-parser, though, because opm-parser has a very hard time to deal with user specified scalar types. (these are required because the local-AD code works that way and opm-parser can't properly deal with them mainly because it uses the traditional header/source file split. Also, IMO it is not opm-parser's job to deal with such implementation details of the simulator.)
- some consistency checks (e.g. the endpoint scaling related ones) can only be done with a full view of the deck. since opm-material requires to have this view anyway, IMO it makes makes more sense to piggy-back that instead copying everything to opm-parser and have consistency nightmares
- simple checks done by the parser (e.g., is a column monotonous and ascending) are not done by the opm-material code (I hope)

hopefully this explanation clears the picture a bit.

> I would actually think that it should be possible to collapse this to only use the classes from opm-parser, but I have not looked into this in detail.

Of course it is possible (because almost everything is possible ;)), but as far as I can see, this would require a *huge* amount of work and a far-reaching redesign of opm-parser. The real question is: would it be *smart*?

> > And then - everything is copied to even another datastructure in opm-core.
>
> I don't think that is true any more, but it was before we switched to opm-material.

I agree with @atgeirr. My idea of that subject is that the parser provides the data specified by the deck in a (relatively) easily accessible form which is then used by the downstream code to create data structures adapted to its specific needs. maybe there are still some redundancies for material-related stuff, but if this is the case I see them as a temporary measure.

> So the question is then: does the opm-material code check the validity of its input tables or not? 

as far as I'm aware of: no. (it only does the higher-level checks.)

**Comment by atgeirr** [comment]
From this discussion it seems to me that we are actually not in a very bad place. There seems to be little duplication of checking effort (which in some sense was the start of this issue), and bad tables seems to be well taken care of, provided that one runs the relperm diagnostics.

We have no way of forcing the user to run the diagnostics, but all variants of Flow do, so I am not too worried. I'll close the issue now, thanks for the input.

**Comment by qilicun** [comment]
Thanks for the discussion here! I think relperm diagnostics has some same checking with opm-material, but the purpose is not the same. opm-material  needs to ensure that value is valid before computing the properties. But originally, the intention of relperm diagnostics is to provide a stand-alone binary for the user to have a full picture of the saturation functions in the deck they have. In the later, I hope relperm diagnostics can be fused into flow much more smoother.
