### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-core#938]
See: https://github.com/OPM/opm-material/issues/104

**Comment by bska** [comment]
Yeah... (#935)

It's sort of a chicken and egg problem.  This particular test, and the associate diagnostics utility, is **supposed** to find the inconsistent table data (positive water relperm at connate water saturation) and warn about it.  The interactions and unclear assumptions between opm-material, opm-parser, and opm-core does however lead to the testing being less useful than it could be.

**Comment by andlaus** [comment]
@bska: I think the main problem rather was that this issue was only detected after the relperm diagnostics tool was merged into opm-core. (i.e., nobody bothered to compile and run the tests in debug mode before it was merged).

Anyway, the issue hopefully is fixed now.

**Comment by bska** [comment]
> I think the main problem rather was that this issue was only detected after the relperm diagnostics tool was merged into opm-core.

True.

> nobody bothered to compile and run the tests in debug mode before it was merged

I'm not entirely sure what you mean by that statement.  I've been running tests in debug mode since the OPM project was started.  In this particular case the test data itself ([`tests/relpermDiagnostics.DATA`](https://github.com/OPM/opm-core/blob/master/tests/relpermDiagnostics.DATA)) did not exist until #929 was merged into master.  It is certainly arguable that the maintainer merging #929 should run the new tests in both debug and release mode before actually merging the PR, but that's not the same as saying no-one ever runs tests in debug mode.

**Comment by andlaus** [comment]
> I'm not entirely sure what you mean by that statement. 

simple: because asserts only bite if the NDEBUG macro is not defined, and there where no relevant opm-material changes between the time when the relperm diagnostics PR was opened and when it was merged, the testing directly before the merge (and the development!?) must have happened purely using release mode. After the act, the issue was discovered. (Given that it is not very severe I think it is not worth bothering about it too much.)

> but that's not the same as saying no-one ever runs tests in debug mode.

I haven't done so -- and I don't want to blame anybody for this --, but in this particular instance it must have been that way for the pre-merge testing. (keep up your good work, btw.)
